### ISSUE TITLE
Stil i WEB-FROM

### ISSUE THREAD

**Issue by AndrineCF** [AndrineCF/GRUPPE-REPOSITORY#21]

**Comment by steina021** [comment]
![image](https://user-images.githubusercontent.com/112163114/208256930-30f3d1b1-0366-4a87-9d4b-7a1a25939058.png)
Få skriften på sidene lengere inn....

**Comment by jonhovd** [comment]
Har fått skriften lengere inn på Web-form i styling-web-form branchen.

**Comment by AndrineCF** [comment]
Det har blitt lagt to isuser av dette problemmet dermed bruker den som blitt oppdatert sist
