### ISSUE TITLE
Lager tester for how we roll

### ISSUE THREAD

**Issue by AndrineCF** [AndrineCF/GRUPPE-REPOSITORY#22]

**Comment by RuneU** [comment]
Noe usikker på hvordan å lage tester for canvas elementet.

 Har lagd litt sån bare basic console.log for hoved output listen og sammenligner dei med console.assert.

**Comment by RuneU** [comment]
ser det er mye folk som bruker noe som heter "Jest" for testing. Men ettersom vi ikke har hatt noe om dette så er jeg usikker på hvordan jeg skal gjøre det.
