### ISSUE TITLE
Tilbake knapp på web-form

### ISSUE THREAD

**Issue by AndrineCF** [AndrineCF/GRUPPE-REPOSITORY#24]

**Comment by steina021** [comment]
Når jeg skal lage knappen, må jeg starte i index eller web raport filen? 
Kan jeg lage knappen i en div container ved å bruke laben eller input?
Skjønner jeg må bruke html først, så style og evnt java for å få den til å fungere.

**Comment by AndrineCF** [comment]
> Når jeg skal lage knappen, må jeg starte i index eller web raport filen? Kan jeg lage knappen i en div container ved å bruke laben eller input? Skjønner jeg må bruke html først, så style og evnt java for å få den til å fungere.

Skal være en knapp i WEB-RAPPRT.html som skal gå til index.html filen. På hvordan du skal gøre det så ville jeg sett på index.html  som allerede har noe knapper kos det har blitt gjort der

**Comment by steina021** [comment]
> > Når jeg skal lage knappen, må jeg starte i index eller web raport filen? Kan jeg lage knappen i en div container ved å bruke laben eller input? Skjønner jeg må bruke html først, så style og evnt java for å få den til å fungere.
> 
> Skal være en knapp i WEB-RAPPRT.html som skal gå til index.html filen. På hvordan du skal gøre det så ville jeg sett på index.html som allerede har noe knapper kos det har blitt gjort der

Fant ut av hvor nå, har stylet og plassert den som "button" i web-FORM. Eneste problemet jeg har er at knappen ikke funker til å gå tilbake til "home-pagen"

**Comment by AndrineCF** [comment]
Kunne du lagt til kode delen til knapp her? Kan sjekke om æ ser noe

**Comment by AndrineCF** [comment]
Mente ikke å lukke denne issues

**Comment by steina021** [comment]
> Kunne du lagt til kode delen til knapp her? Kan sjekke om æ ser noe

<div>
                <button class="button-home" onclick="location.href='./index.html';">Home</button>

**Comment by steina021** [comment]
> Kunne du lagt til kode delen til knapp her? Kan sjekke om æ ser noe

<div>
                <button class="button-home" onclick="location.href='./index.html';">Home</button>
<div>

**Comment by steina021** [comment]
![image](https://user-images.githubusercontent.com/112163114/206720102-1daa0d83-70a8-47d3-953e-755de0d62ce3.png)


Var dette jeg skrev i web- form <div>

**Comment by AndrineCF** [comment]
Vel det er kanskje litt komplisert metode å gjøre det på? Æ trur æ skjønner kva skjer, men kunne du forklare tankegang på hvorfor å gjør det som?

**Comment by steina021** [comment]
> Vel det er kanskje litt komplisert metode å gjøre det på? Æ trur æ skjønner kva skjer, men kunne du forklare tankegang på hvorfor å gjør det som?

vil at når du klikker på knappen skal den få deg til index.html siden, som er forsiden vår...

**Comment by steina021** [comment]
> Vel det er kanskje litt komplisert metode å gjøre det på? Æ trur æ skjønner kva skjer, men kunne du forklare tankegang på hvorfor å gjør det som?

Jeg gjøre det på en annen måte nå, en enklere en, fikk knappen til å fungere, mangler bare å style den

**Comment by steina021** [comment]
> Vel det er kanskje litt komplisert metode å gjøre det på? Æ trur æ skjønner kva skjer, men kunne du forklare tankegang på hvorfor å gjør det som?

![Skjermbilde 2022-12-12 151615](https://user-images.githubusercontent.com/112163114/207067949-6b8d4a43-3fa0-4a02-b617-5ce037b899a4.png)
brukte denne kodingen i stedet, men har utfordringer med å style knappen

**Comment by Befalen** [comment]
Stylet tilbake-knappen lik som de andre knappene, men får ikke til å fungere den som en knapp.
