### ISSUE TITLE
Style web-rapport

### ISSUE THREAD

**Issue by steina021** [AndrineCF/GRUPPE-REPOSITORY#27]

**Comment by steina021** [comment]
![image](https://user-images.githubusercontent.com/112163114/208256781-b466e2d3-760b-4c4c-b5f4-88359dce88a6.png)
Skape større mellomrom mellom strekene og navn på katogoriene på siden ??

**Comment by Befalen** [comment]
Lagt til "Navn" på begge sidene av linjene
