### ISSUE TITLE
Må vi lage flere flagg? 

### ISSUE THREAD

**Issue by B4KO** [AndrineCF/GRUPPE-REPOSITORY#9]
Tror vi må lage flere flagg ettersom oppgaven tilsier "det skal være avstand mellom flaggene" på hver deloppgave.

**Comment by AndrineCF** [comment]
Vel skader ikke å lage mer flagg da for sikkerhet skyld

**Comment by B4KO** [comment]
Bekreftet Ja. 3 flagg med hver methode
